# Generated by Django 4.1.6 on 2023-02-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
