# Generated by Django 4.1.6 on 2023-02-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0002_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='dish_name',
            field=models.CharField(default='TestDishName', max_length=200),
        ),
    ]
